models:
  - name: openai
    provider: openai
    options:
      model: gpt-4.1-nano

tools:
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  - name: echo
    type: builtin
    description: Echo a message

include:
  - templates/roles/coder.yaml

agents:
  test-agent:
    role: System
    model: openai
    prompt: |
      You are a test agent. Always respond with exactly: "I am using model: [MODEL_NAME]"
    tools: ["echo"]

tasks:
  - agent: test-agent
    input: "What model are you using?"
