theme: dark
models:
  - name: openai
    provider: openai
    options:
      # API key will be read from $OPENAI_KEY environment variable
      model: gpt-4o
routes:
  - if_contains: [""]
    model: openai
tools:
  # Only custom/specialized tools - agents use native shell commands for basic operations
  - name: branch-tidy
    type: builtin
    description: Delete all local Git branches except the current one
  - name: agent
    type: builtin
    description: Delegate to another agent

# Disable sandbox to avoid cri-shim dependencies for now
sandbox:
  engine: disabled

# Include agent role definitions
include:
  - templates/roles/agent_0.yaml
  - templates/roles/coder.yaml
