theme: dark
models:
  - name: openai
    provider: openai
    options:
      # API key will be read from $OPENAI_KEY environment variable
      model: gpt-4o
routes:
  - if_contains: [""]
    model: openai
tools:
  # All builtin tools available - sandboxing disabled for now
  - name: echo
    type: builtin
    description: Repeat a string
  - name: ping
    type: builtin
    description: Ping a host
  - name: bash
    type: builtin
    description: Execute a bash command
  - name: branch-tidy
    type: builtin
    description: Delete all local Git branches except the current one
  - name: fetch
    type: builtin
    description: Download content from a URL
  - name: glob
    type: builtin
    description: Find files by pattern
  - name: grep
    type: builtin
    description: Search file contents
  - name: ls
    type: builtin
    description: List directory contents
  - name: view
    type: builtin
    description: View file contents
  - name: write
    type: builtin
    description: Create or overwrite a file
  - name: edit
    type: builtin
    description: Update an existing file
  - name: patch
    type: builtin
    description: Apply a unified diff patch
  - name: agent
    type: builtin
    description: Delegate to another agent

# Disable sandbox to avoid cri-shim dependencies for now
sandbox:
  engine: disabled

# Include agent role definitions
include:
  - templates/roles/agent_0.yaml
  - templates/roles/coder.yaml
