site_name: Agentry
site_url: https://marcodenic.github.io/agentry/
docs_dir: docs
nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - API: api.md
  - VS Code Extension: vscode-extension.md
  - Registry: registry/index.html
theme:
  name: material
plugins:
  - search
