agents:
  planner:
    model: mock
  executor:
    model: mock
    tools: [bash]
tasks:
  - sequential:
      - agent: planner
        input: "Write a Dockerfile for a Go service"
      - agent: executor
        input: |
          echo 'FROM golang:1.23-alpine\nWORKDIR /app\nCOPY . .\nRUN go build -o server ./cmd/server\nCMD ["./server"]' > Dockerfile
      - agent: executor
        input: "docker build -t agentry-demo ."
