apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentry-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentry-autoscaler
  template:
    metadata:
      labels:
        app: agentry-autoscaler
    spec:
      serviceAccountName: default
      containers:
      - name: autoscaler
        image: agentry:latest
        command: ["/app/cmd/autoscaler"]
        env:
        - name: NATS_URL
          value: nats://nats:4222
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

