agents:
  planner:
    model: mock
  executor:
    model: mock
    tools: [bash]
tasks:
  - sequential:
      - agent: planner
        input: "Explain how to convert CSV data to JSON using shell utilities."
      - agent: executor
        input: "Create a script that converts sample.csv to sample.json."
