{{- if .Values.autoscaler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentry.fullname" . }}-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "agentry.name" . }}-autoscaler
  template:
    metadata:
      labels:
        app: {{ include "agentry.name" . }}-autoscaler
    spec:
      serviceAccountName: default
      containers:
      - name: autoscaler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/app/cmd/autoscaler"]
        env:
        - name: NATS_URL
          value: {{ .Values.queue.address | quote }}
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - "-deployment={{ include \"agentry.fullname\" . }}"
          - "-factor={{ .Values.autoscaler.scaleFactor }}"
          - "-min={{ .Values.autoscaler.minReplicas }}"
          - "-max={{ .Values.autoscaler.maxReplicas }}"
          - "-poll={{ .Values.autoscaler.pollInterval }}"
{{- end }}
