apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agentry.fullname" . }}-data
spec:
  accessModes:
  - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
