# Configuration for testing persistent agents with Claude
models:
  - name: anthropic
    provider: anthropic
    options:
      model: claude-3-opus-20240229
      temperature: 0.1

tools:
  # Core agent delegation tool
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  
  # Basic tools for testing
  - name: echo
    type: builtin
    description: Repeat a string
  - name: view
    type: builtin
    description: View file contents
  - name: create
    type: builtin
    description: Create a new file
  - name: ls
    type: builtin
    description: List directory contents

# Phase 2A.1: Enable persistent agents
persistent_agents:
  enabled: true
  port_start: 9001
  port_end: 9010
