model:
  provider: "openai"
  name: "gpt-4"
  apiKey: "${OPENAI_API_KEY}"

# Enable persistent agents for session testing
persistent_agents:
  enabled: true
  port_start: 9020  # Use different port range to avoid conflicts
  port_end: 9030

# Basic tool registry
tools:
  - name: "echo"
    command: "echo"
    description: "Echo input back"
  - name: "pwd"
    command: "pwd"
    description: "Show current directory"
