# Configuration for testing persistent agents with basic tools
models:
  - name: openai
    provider: openai
    options:
      model: gpt-4.1-nano
      temperature: 0.1

# Enable persistent agents for session testing
persistent_agents:
  enabled: true
  port_start: 9020  # Use different port range to avoid conflicts
  port_end: 9030

# Basic tool registry
tools:
  - name: echo
    type: builtin
    description: Echo input back
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
