# Configuration for minimal persistent agent testing
models:
  - name: openai
    provider: openai
    options:
      model: gpt-4.1-nano
      temperature: 0.1

# Enable persistent agents
persistent_agents:
  enabled: true
  port_start: 9040
  port_end: 9050

# Minimal tools to avoid conflicts
tools:
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
