# Configuration for advanced testing with enhanced tools and multiple models
models:
  - name: openai
    provider: openai
    options:
      model: gpt-4.1-nano
      temperature: 0.1
  - name: anthropic
    provider: anthropic
    options:
      model: claude-instant

# Enhanced tool set with better exploration capabilities
tools:
  # Core built-in tools
  - name: echo
    type: builtin
    description: Repeat a string
  - name: ping
    type: builtin
    description: Ping a host
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  - name: fetch
    type: builtin
    description: Download content from HTTP/HTTPS URLs
  - name: patch
    type: builtin
    description: Apply a unified diff patch
  - name: sysinfo
    type: builtin
    description: Get system information

  # File operation tools - Critical for intelligent agents
  - name: read_lines
    type: builtin
    description: Read specific lines from a file
  - name: edit_range
    type: builtin
    description: Replace a range of lines in a file
  - name: insert_at
    type: builtin
    description: Insert lines at a specific position
  - name: search_replace
    type: builtin
    description: Advanced search/replace with regex
  - name: fileinfo
    type: builtin
    description: Get comprehensive file information - CRITICAL for discovery
  - name: view
    type: builtin
    description: Enhanced file viewing with line numbers
  - name: create
    type: builtin
    description: Create a new file with content
  - name: grep
    type: builtin
    description: Search file contents - ESSENTIAL for smart discovery

  # Enhanced exploration tools
  - name: ls
    type: builtin
    description: List directory contents - USE FIRST for exploration
  - name: find
    type: builtin
    description: Find files by pattern - CRITICAL for file discovery
  - name: glob
    type: builtin
    description: Find files by glob pattern

  # Web tools
  - name: web_search
    type: builtin
    description: Search the web for information
  - name: read_webpage
    type: builtin
    description: Extract content from web pages
  - name: api
    type: builtin
    description: Make HTTP/REST API calls
  - name: download
    type: builtin
    description: Download files from URLs

  # Shell tools for all platforms
  - name: powershell
    type: builtin
    description: Execute PowerShell commands
  - name: cmd
    type: builtin
    description: Execute cmd.exe commands
  - name: bash
    type: builtin
    description: Execute bash commands
  - name: sh
    type: builtin
    description: Execute shell commands

  # Git tools
  - name: branch-tidy
    type: builtin
    description: Delete all local Git branches except the current one

# Include role configurations
include:
  - ../templates/roles/agent_0.yaml
  - ../templates/roles/coder.yaml
  - ../templates/roles/tester.yaml
  - ../templates/roles/writer.yaml
  - ../templates/roles/researcher.yaml
  - ../templates/roles/team_planner.yaml
