# Configuration for testing agent delegation functionality
models:
  - name: mock
    provider: mock

# Basic tool set for delegation testing
tools:
  - name: echo
    type: builtin
    description: Repeat a string
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  - name: ping
    type: builtin
    description: Ping a host

env:
  MAX_ITERATIONS: "3"
  
agent:
  max_iterations: 3
