# Test configuration for tool testing
# This extends the smart-config.yaml with test-specific settings

models:
  - name: openai
    provider: openai
    options:
      model: gpt-4-turbo
      temperature: 0.1
      max_tokens: 2000
  - name: anthropic
    provider: anthropic
    options:
      model: claude-3-haiku-20240307
      temperature: 0.1
      max_tokens: 2000

# All built-in tools for comprehensive testing
tools:
  # Core built-in tools
  - name: echo
    type: builtin
    description: Repeat a string
  - name: ping
    type: builtin
    description: Ping a host
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  - name: fetch
    type: builtin
    description: Download content from HTTP/HTTPS URLs
  - name: patch
    type: builtin
    description: Apply a unified diff patch
  - name: sysinfo
    type: builtin
    description: Get system information

  # File operation tools
  - name: read_lines
    type: builtin
    description: Read specific lines from a file
  - name: edit_range
    type: builtin
    description: Replace a range of lines in a file
  - name: insert_at
    type: builtin
    description: Insert lines at a specific position
  - name: search_replace
    type: builtin
    description: Advanced search/replace with regex
  - name: fileinfo
    type: builtin
    description: Get comprehensive file information
  - name: view
    type: builtin
    description: Enhanced file viewing with line numbers
  - name: create
    type: builtin
    description: Create a new file with content
  - name: grep
    type: builtin
    description: Search file contents

  # Enhanced exploration tools
  - name: ls
    type: builtin
    description: List directory contents
  - name: find
    type: builtin
    description: Find files by pattern
  - name: glob
    type: builtin
    description: Find files by glob pattern

  # Web tools
  - name: web_search
    type: builtin
    description: Search the web for information
  - name: read_webpage
    type: builtin
    description: Extract content from web pages
  - name: api
    type: builtin
    description: Make HTTP/REST API calls
  - name: download
    type: builtin
    description: Download files from URLs

  # Shell tools
  - name: bash
    type: builtin
    description: Execute bash commands
  - name: sh
    type: builtin
    description: Execute shell commands
  - name: powershell
    type: builtin
    description: Execute PowerShell commands
  - name: cmd
    type: builtin
    description: Execute cmd.exe commands

  # Git tools
  - name: branch-tidy
    type: builtin
    description: Delete all local Git branches except the current one

# Test-specific settings
settings:
  # max_iterations removed; agents run until completion
  timeout: 30
  enable_trace: true
  sandbox_mode: true
  
# Test role for tool testing
roles:
  - name: tool_tester
    description: |
      You are a comprehensive tool testing agent. Your job is to test each tool thoroughly and report on its functionality.
      
      For each tool test:
      1. Use the tool as requested
      2. Verify the output is correct
      3. Test edge cases when possible
      4. Report any errors or unexpected behavior
      5. Provide a summary of the tool's functionality
      
      Be thorough but efficient. Test each tool's core functionality and document any issues you encounter.
    
    instructions: |
      When testing tools:
      - Follow the exact prompt instructions
      - Use tools in the order specified
      - Report both successes and failures
      - Include relevant output in your response
      - Suggest improvements if you notice issues
      
      If a tool fails:
      - Try to understand why it failed
      - Test with simpler inputs if possible
      - Report the error clearly
      - Continue with other tests
      
      Always be helpful and thorough in your testing approach.
