models:
  - name: mock
    provider: mock
  - name: openai
    provider: openai
    options:
      env_key: OPENAI_KEY
routes:
  - if_contains: [""]
    model: openai
tools:
  - name: echo
    type: builtin
    description: Repeat a string
  - name: ping
    type: builtin
    description: Ping a host
  - name: local_shell
    command: echo hello
    description: Uses shell (optional, advanced)
