theme: dark
models:
  - name: mock
    provider: mock
  - name: openai
    provider: openai
    options:
      # API key; defaults to $OPENAI_KEY if omitted
      key: ""
      # Model name; defaults to gpt-4o if omitted
      model: gpt-4o
routes:
  - if_contains: [""]
    model: openai
tools:
  # Built-in tools available in Agentry. Add or remove as needed.
  - name: echo
    type: builtin
    description: Repeat a string
  - name: ping
    type: builtin
    description: Ping a host
  # OS-specific shell tools (only register tools available on your OS)
  # On Windows: powershell, cmd
  # On Unix/Linux/macOS: bash, sh
  - name: powershell
    type: builtin
    description: Execute PowerShell commands (Windows only)
  - name: cmd
    type: builtin
    description: Execute cmd.exe commands (Windows only)
  # Uncomment these on Unix/Linux/macOS:
  # - name: bash
  #   type: builtin
  #   description: Execute bash commands (Unix/Linux/macOS only)
  # - name: sh
  #   type: builtin
  #   description: Execute shell commands (Unix/Linux/macOS only)
  - name: branch-tidy
    type: builtin
    description: Delete all local Git branches except the current one
  - name: fetch
    type: builtin
    description: Download content from a URL
  - name: patch
    type: builtin
    description: Apply a unified diff patch
  - name: agent
    type: builtin
    description: Delegate tasks to another agent
  - name: mcp
    type: builtin
    description: Connect to an MCP server
    address: mcp.example.net:7777
  - name: local_shell
    command: echo hello
    description: Uses shell (optional, advanced)
    engine: cri
metrics: true
# default sandbox engine for unprivileged tools
sandbox:
  engine: disabled
# send spans to an OTLP collector
# collector: localhost:4318
# path to SQLite DB for conversation history
# store: path/to/db.sqlite
# delete sessions older than this duration (e.g. 168h = 7 days)
session_ttl: 168h
# cleanup check interval
session_gc_interval: 1h
# Add default team planner role for team mode
include:
  - templates/roles/team_planner.yaml
