openapi: 3.0.0
servers:
  - url: http://localhost:8080
paths:
  /echo:
    post:
      operationId: echo
      summary: Echo input
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required: [text]
      responses:
        '200':
          description: ok
