agents:
  alice:
    model: mock
  bob:
    model: mock
  carol:
    model: mock
tasks:
  - parallel:
      - agent: alice
        input: "Propose a project idea."
      - agent: bob
        input: "Provide feedback on the idea."
      - agent: carol
        input: "Summarise the discussion."
