name: Chaos Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  chaos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run chaos script
        run: ./scripts/chaos.sh
