name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Ensure LICENSE exists
        shell: bash
        run: test -f LICENSE

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check gofmt (Unix-like only)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          diff=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$diff" ]; then echo "gofmt needed:" && echo "$diff" && exit 1; fi

      - name: Check gofmt (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $goFiles = git ls-files '*.go'
          $diff = gofmt -l $goFiles
          if ($diff) {
            Write-Host "gofmt needed:"
            Write-Host $diff
            exit 1
          }

      - name: Run go vet
        run: go vet ./...

      - name: Install and run golangci-lint
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        timeout-minutes: 8
        continue-on-error: true
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          $(go env GOPATH)/bin/golangci-lint run --timeout=3m

      - name: Run Go tests
        shell: bash
        timeout-minutes: 10
        run: go test ./...

      - name: Smoke test CLI version
        shell: bash
        timeout-minutes: 2
        run: go run ./cmd/agentry --version
