name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Ensure LICENSE exists
        shell: bash
        run: test -f LICENSE

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install and run golangci-lint
        shell: bash
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          $(go env GOPATH)/bin/golangci-lint run

      - name: Run Go tests
        shell: bash
        run: go test ./...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install and test TS SDK
        working-directory: ts-sdk
        shell: bash
        run: |
          npm ci
          npm test

      - name: Run agentry eval
        shell: bash
        run: go run ./cmd/agentry eval examples/.agentry.yaml
